# include: package:flutter_lints/queries.yaml # O la versión que uses

analyzer:
  errors:
    # Esto silencia avisos específicos si te molestan mucho
    todo: ignore
    invalid_annotation_target: ignore

linter:
  rules:
    # Aquí puedes desactivar reglas que te den muchos warnings
    prefer_const_constructors: false
    prefer_final_fields: false
    use_key_in_widget_constructors: false